import { AuthProvider } from './Providers/Provider'
import './globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aayush',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Loginmodel/>
      
      <main>{children}</main>
      </body>
=======
      <body className={inter.className}><AuthProvider>{children}</AuthProvider></body>
    </html>
  )
}
