import { AuthProvider } from './Providers/Provider'
import ToastProvider from './Providers/Toastprovider'
import './globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aayush',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><AuthProvider>
        <ToastProvider/>{children}</AuthProvider></body>
    </html>
  )
}
